config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords, :registrations], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
    post 'customers', to: 'public/registrations#create', as: :customer_registration
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    resources :customers, only: [:index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    get 'search' => 'items#search'
  end

  scope module: :public do
    root to:'homes#top'
    get '/about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resource :customers, only: [:edit, :update]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :new, :show, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer

   validates :amount, presence: true, numericality: {only_integer: true}

   def subtotal
     item.with_tax_price * amount
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

   def address_display
     '〒' + postal_code + ' ' + address
   end
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy

   validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end

  def self.search(keyword)
  where(["name like?", "%#{keyword}%"])
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum pay_method: { credit_card: 0, transfer: 1 }
  enum status: { pay_waiting: 0, pay_check: 1, producing: 2, ship_waiting: 3, shipping: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { unable: 0, produce_wating: 1, producing: 2, complete: 3 }

  def subtotal
     item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render new_admin_item_path
    end
  end

  def show
  end

  def edit
  end
  
  def search
  @items = Item.search(params[:keyword])
  @keyword = params[:keyword]
  render "index"
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_available)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
    if @order.status == Order.statuses.key(1)
      @order_details.each do |order_detail|
        order_detail.making_status = OrderDetail.making_statuses.key(1)
        order_detail.save
      end
    end

    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Customer
     customers_my_page_path
    when Admin
     admin_homes_top_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0">
         <h2><span class="badge">ジャンル編集</span></h2>
        <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
         <% if @genre.errors.any? %>
          <div id="error_explanation" >
           <h3><%= @genre.errors.count %> error prohibited this obj from being saved: </h3>
           <% @genre.errors.full_messages.each do |message| %>
            <ul>
             <li> <%= message %></li>
            </ul>
           <% end %>
          </div>
         <% end %>
        <div class="row">
          <div class="col-4">
            <div class="field">
              <%= f.label :ジャンル名 %><br />
              <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
            </div>
          </div>
        </div>
        <div class="actions"><br />
         <%= f.submit "変更を保存", class:"btn btn-success" %>
        </div>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/genres/index.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row">
      <div class="col-12 px-5 px-sm-0">
        <h2><span class="badge">ジャンル一覧・追加</span></h2>
        <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
         <% if @genre.errors.any? %>
          <div id="error_explanation" >
           <h3><%= @genre.errors.count %> error prohibited this obj from being saved: </h3>
           <% @genre.errors.full_messages.each do |message| %>
            <ul>
             <li> <%= message %></li>
            </ul>
           <% end %>
          </div>
         <% end %>
         <p id="notice"></p>
        <div class="row">
          <div class="col-3">
            <p>ジャンル名</p>
          </div>
          <div class="col-3">
            <div class="field">
              <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
            </div>
          </div>
          <div class="col-3">
            <div class="actions">
                <%= f.submit "新規登録", class:"btn btn-success" %>
            </div>
          </div>
        </div>
        <% end %><br />
        <div class="col-5">
          <table class="table table-hover table-inverse">
        <thead class="thead-light">
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to '編集する', edit_admin_genre_path(genre.id), class:"btn btn-success", role:"button" %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
        </div>

      </div>
    </div>
</div>

app/views/admin/items/edit.html.erb
<h1>Admin::Items#edit</h1>
<p>Find me in app/views/admin/items/edit.html.erb</p>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"></p>
      <div class="row">
        <div class="col-10">
          <h2><span class="badge">商品一覧</span></h2>
        </div>
        <div class="col-2">
          <%= link_to '追加', new_admin_item_path, class:"btn btn-success" %>
        </div>
      </div>
      <p id="notice"></p>
      <table class="table table-hover table-inverse">
        <thead class="thead-light">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜き価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= item.name %></td>
              <td><%= item.price %>円</td>
              <td><%= item.genre.name %></td>
              <% if item.is_available %>
                <td class="state">販売中</td>
              <% else %>
                <td>販売停止中</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"></p>
      <h2><span class="badge">商品新規登録</span></h2>
      <p id="notice"></p>
    </div>
  </div>
</div>
  <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
      <% if @item.errors.any? %>
          <div id="error_explanation" >
           <h3><%= @item.errors.count %> error prohibited this obj from being saved: </h3>
           <% @item.errors.full_messages.each do |message| %>
            <ul>
             <li> <%= message %></li>
            </ul>
           <% end %>
          </div>
         <% end %>
        <div class="row">
          <div class="col-3"></div>
          <div class="col-2">
            <p>商品画像</p>
          </div>
          <div class= "col-4">
            <div class="field">
              <%= f.file_field :image, accept: "image/*" %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-3"></div>
          <div class="col-2">
            <p>商品名</p>
          </div>
          <div class="col-4">
            <%= f.text_field :name, include_blank: "商品名"%>
          </div>
        </div>
        <div class="row">
          <div class="col-3"></div>
          <div class="col-2">
            <p>商品説明</p>
          </div>
          <div class="col-4">
            <%= f.text_area :introduction %>
          </div>
        </div>
        <div class="row">
          <div class="col-3"></div>
          <div class="col-2">
            <p>ジャンル</p>
          </div>
          <div class="col-4">
             <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
          </div>
        </div>
        <div class="row">
          <div class="col-3"></div>
          <div class="col-2">
            <p>税抜価格</p>
          </div>
          <div class="col-4">
            <%= f.text_field :price %>　円
          </div>
        </div>
        <div class="row">
          <div class="col-3"></div>
          <div class="col-2">
            <p>販売ステータス</p>
          </div>
          <div class="col-4">
            <%= f.radio_button :is_available, true %>
            <%= f.label :is_available, '販売中', value: true %>
            <%= f.radio_button :is_available, false %>
            <%= f.label :is_available, '販売停止中', value: false %>
          </div>
        </div>

        <div class="row">
          <div class = "col-5"></div>
          <div class ="col-3">
            <div class="actions"><br />
              <%= f.submit "新規登録", class:"btn btn-success" %>
            </div>
          </div>
        </div>


       <% end %>
</div>

app/views/admin/items/show.html.erb
<h1>Admin::Items#show</h1>
<p>Find me in app/views/admin/items/show.html.erb</p>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"></p>
      <h2><span class="badge">注文履歴一覧</span></h2>
      <p id="notice"></p>
      <table class="table table-hover table-inverse">
        <thead class="thead-light">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to admin_order_path(order) do%>
                    <%= l order.created_at %>
                  <% end %>
              </td>
              <td><%= order.customer.first_name %><%= order.customer.last_name %></td>
              <% @sum = 0 %>
              <% order.order_details.each do |order_detail| %>
               <% @sum += order_detail.amount %>
              <% end %>
              <td><%= @sum %></td>
              <td><%= order.status_i18n %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <p id="notice"></p>
       <h2><span class="badge">　注文履歴詳細</span></h2>
       <div class="row">
         <div class="col-2">
           <h3><span class="badge">購入者</span></h3>
         </div>
         <div class="col-10">
           <h4><%= @order.customer.first_name + @order.customer.last_name %></h4>
         </div>
       </div>
       <div class="row">
         <div class="col-2">
           <h3><span class="badge">注文日</span></h3>
         </div>
         <div class="col-10">
           <h4><%= @order.created_at.strftime('%Y/%m/%d') %></h4>
         </div>
      </div>
      <div class="row">
         <div class="col-2">
           <h3><span class="badge">配送先</span></h3>
         </div>
         <div class="col-10">
           <h4>
             <%= '〒' + @order.postal_code + ' ' + @order.address %><br/>
             <%= @order.name %>
           </h4>
         </div>
      </div>
      <div class="row">
         <div class="col-2">
           <h3><span class="badge">支払方法</span></h3>
         </div>
         <div class="col-10">
           <h4><%= @order.pay_method_i18n %></h4>
         </div>
       </div>
       <div class="row">
         <div class="col-2">
           <h3><span class="badge">注文ステータス</span></h3>
         </div>
         <div class="col-10">
           <p></p>
           <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
            <%= f.select :status, options_for_select([[Order.statuses_i18n[:pay_waiting], Order.statuses.key(0)], [Order.statuses_i18n[:pay_check], Order.statuses.key(1)], [Order.statuses_i18n[:shipping], Order.statuses.key(4)]]), include_blank: @order.status_i18n %>
            <%= f.submit "更新", class:"btn btn-success" %>
           <% end %>
         </div>
       </div>
       <p id="notice"></p>
       <div class="row">
         <div class="col-8">
           <table class="table table-hover table-inverse">
            <thead class="thead-light">
              <tr>
                <th>商品名</th>
                <th>単価（税込み）</th>
                <th>数量</th>
                <th>製作ステータス</th>
              </tr>
            </thead>
          <tbody>
              <% @sum = 0 %>
           <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.item.with_tax_price %></td>
               <% @sum += order_detail.subtotal %>
              <td><%= order_detail.amount %></td>
              <td>
                  <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                    <%= f.select :making_status, options_for_select([[OrderDetail.making_statuses_i18n[:producing], OrderDetail.making_statuses.key(2)], [OrderDetail.making_statuses_i18n[:complete], OrderDetail.making_statuses.key(3)]]), include_blank: order_detail.making_status_i18n %>
                    <%= f.submit "更新", class:"btn btn-success" %>
                  <% end %>
              </td>
             </tr>
            <% end %>
           </tbody>
          </table>
          </div>
          <div class="col-4">
              <div class="row">　</div>
              <div class="row">　</div>
              <div class="row">
                  <div class="col-6">
                      <h3><span class="badge">商品合計</span></h3>
                  </div>
                  <div class="col-6">
                      <h3><span class="badge"><%= @sum %> 円</span></h3>
                  </div>
              </div>
              <div class="row">
                  <div class="col-6">
                      <h3><span class="badge">送料</span></h3>
                  </div>
                  <div class="col-6">
                      <h3><span class="badge"><%= @order.shipping_fee %>円</span></h3>
                  </div>
              </div>
              <div class="row">
                  <div class="col-6">
                      <h3><span class="badge">請求金額合計</span></h3>
                  </div>
                  <div class="col-6">
                      <h3><span class="badge"><%= @sum + @order.shipping_fee %>円</span></h3>
                  </div>
                </div>
          </div>
       </div>
    </div>
  </div>
</div>