config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords, :registrations], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :customer do
    get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
    post 'customers', to: 'public/registrations#create', as: :customer_registration
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    resources :customers, only: [:index]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
    get 'search' => 'items#search'
  end

  scope module: :public do
    root to:'homes#top'
    get '/about' => 'homes#about'
    get 'customers/my_page' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resource :customers, only: [:edit, :update]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :new, :show, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
   belongs_to :item
   belongs_to :customer

   validates :amount, presence: true, numericality: {only_integer: true}

   def subtotal
     item.with_tax_price * amount
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

   def address_display
     '〒' + postal_code + ' ' + address
   end
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy

   validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end

  def self.search(keyword)
  where(["name like?", "%#{keyword}%"])
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum pay_method: { credit_card: 0, transfer: 1 }
  enum status: { pay_waiting: 0, pay_check: 1, producing: 2, ship_waiting: 3, shipping: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { unable: 0, produce_wating: 1, producing: 2, complete: 3 }

  def subtotal
     item.with_tax_price * amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render new_admin_item_path
    end
  end

  def show
  end

  def edit
  end
  
  def search
  @items = Item.search(params[:keyword])
  @keyword = params[:keyword]
  render "index"
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_available)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Customer
     customers_my_page_path
    when Admin
     admin_homes_top_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/ea4c56ad7f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <body>
  <% if admin_signed_in? %>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/admin/homes/top">
            <spam>ロゴ</spam>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
          </button>
          <div class="bar">
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
             <li><%= link_to " 商品一覧", admin_items_path, class:"fas fa-shopping-bag nav-link text-light" %></li>
             <li><%= link_to " 会員一覧", admin_customers_path, class:"fas fa-users nav-link text-light" %></li>
             <li><%= link_to " 注文履歴一覧", admin_orders_path, class:"fas fa-clipboard-list nav-link text-light" %></li>
             <li><%= link_to " ジャンル一覧", admin_genres_path, class:"fas fa-dice-d6 nav-link text-light" %></li>
             <li><%= link_to ' logout', destroy_admin_session_path, method: :delete,  class:"fas fa-sign-out-alt nav-link text-light" %></li>
            </ul>
          </div>
            <ul class="navbar-nav ml-auto d-none d-md-block">
              <li>
                <%= form_with url: admin_search_path, method: :get, local: true, class:"d-flex" do |f| %>
                 　　<%= f.text_field :keyword, value: @keyword, class:"form-control me-2", placeholder:"Search" %>
                 　　<%= f.submit "検索", class:"btn btn-outline-success" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    </header>

  <% elsif customer_signed_in? %>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <spam>ロゴ</spam>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
             <li><%= link_to ' マイページ', customers_my_page_path, class:'fas fa-home nav-link text-light' %></li>
             <li><%= link_to ' 商品一覧', items_path, class:'fas fa-shopping-bag nav-link text-light' %></li>
             <li><%= link_to ' カート', cart_items_path, class:'fas fa-shopping-cart nav-link text-light' %></li>
             <li><%= link_to ' logout', destroy_customer_session_path, method: :delete,  class:"fas fa-sign-out-alt nav-link text-light" %></li>
          </ul>
          </div>
        </div>
      </nav>

    </header>

    <% else %>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <spam>LOGO</spam>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
             <li><%= link_to ' Home', root_path, class:'fas fa-home nav-link text-light' %></li>
             <li><%= link_to ' About', about_path, class:'fas fa-link nav-link text-light' %></li>
             <li><%= link_to ' sign up', new_customer_registration_path, class:'fas fa-user-plus nav-link text-light' %></li>
             <li><%= link_to ' login', new_customer_session_path, class:'fas fa-sign-in-alt nav-link text-light' %></li>
            </ul>
          </div>
        </div>
      </nav>

    </header>
  <% end %>
  <%= yield %>
  </body>
</html>